version: '3'
services:
  php:
    build:
      context: docker/php
    #image: php:fpm
    volumes:
    - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./:/var/www

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    links:
      - php

  codepress-mysql:
    container_name: codepress-mysql
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: codepress

  codepress-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: codepress-phpmyadmin
    links:
    - codepress-mysql
    environment:
    - PMA_ARBITRARY=1
    - VIRTUAL_HOST=phpmyadmin.local
    - PMA_PORT=3306
    restart: always
    ports:
    - "8080:80"
